### ISSUE TITLE
Icons not appearing in wb dropdown or tool icons

### ISSUE THREAD

**Issue by concretedog** [davesrocketshop/Rocket#11]
Hi Dave, Excellent work. On my install all the icons are missing. Both the icon on the dropdown workbench and the actual tool icons. 

`10:22:47  Cannot find icon: /home/concretedog/.FreeCAD/Mod/Rocket/Resources/icons/RocketWorkbench.svg
10:23:04  Cannot find icon: /home/concretedog/.FreeCAD/Mod/Rocket/Resources/icons/Rocket_NoseCone.svg
10:23:04  Cannot find icon: /home/concretedog/.FreeCAD/Mod/Rocket/Resources/icons/Rocket_Transition.svg
10:23:04  Cannot find icon: /home/concretedog/.FreeCAD/Mod/Rocket/Resources/icons/Rocket_BodyTube.svg
10:23:04  Cannot find icon: /home/concretedog/.FreeCAD/Mod/Rocket/Resources/icons/Rocket_CenteringRing.svg
10:23:04  Cannot find icon: /home/concretedog/.FreeCAD/Mod/Rocket/Resources/icons/Rocket_Bulkhead.svg
10:23:04  Cannot find icon: /home/concretedog/.FreeCAD/Mod/Rocket/Resources/icons/Rocket_Fin.svg
`

**Comment by davesrocketshop** [comment]
The files are in the release, but if you did a straight unzip, they may be located in /home/concretedog/.FreeCAD/Mod/Rocket-1.0 instead of /home/concretedog/.FreeCAD/Mod/Rocket. If that is the case, rename the folder. If it is not, please grab a screenshot of your /home/concretedog/.FreeCAD/Mod/Rocket folder.

**Comment by concretedog** [comment]
Yes, that has solved it, I had DL'd and unzipped manually,

**Comment by davesrocketshop** [comment]
Good. I'll update the manual install instructions.
