### ISSUE TITLE
Cannot Find Icon

### ISSUE THREAD

**Issue by naiksukhesh** [davesrocketshop/Rocket#59]
i have downloaded the zip file for rocket and later extracted the files from the zip. I created mod folder in FreeCAD and copied the extracted rocket file in this folder. When i open FreeCAD it shown cannot find icon : C:\Users\acer\AppData\Roaming\FreeCAD\Mod/Rocket/Resources/icons/RocketWorkbench.svg.
Please help me to solve this problem as soon as possible

**Comment by davesrocketshop** [comment]
First thing to check is if everything extracted correctly. For example, the 3.0 release will extract as Rocket-3.0.0 instead of Rocket. So check the path names first and make sure they match. If they don't you'll have many issues, not just with the icons.

In general, manual installation is not recommended unless you are knowledgeable enough to debug these issues yourself. Have you tried using the FreeCAD addon manager?

**Comment by davesrocketshop** [comment]
Any update?

**Comment by naiksukhesh** [comment]
Solved the issue no prbs.. changed the file name according to the path mentionedSent from my iPhoneOn 28-Apr-2023, at 6:10 AM, David Carter ***@***.***> wrote:﻿
Any update?
